name: tiendero
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 5.0.0
  flutter_svg: 0.22.0
  rflutter_alert: 2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    -  assets/images/imgs/
    -  assets/images/vectors/

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
            style: italic
          - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
            weight: 100
          - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/montserrat/Montserrat-Light.ttf
            weight: 300
          - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
            weight: 400
            style: normal
          - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
            weight: 500
          - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
            weight: 700
          - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/montserrat/Montserrat-Black.ttf
            weight: 900
